export const products = [
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},
   { "id": "ded6041a-622f-4fb4-81e4-96fcfdad4dff",
    "title": "Ping Pong Championship",
    "description": "Enter the world of Ping Pong Championship and compete against the world's best to become the ultimate champion in this exciting game.",
    "genre": "Sports",
    "released": "2005",
    "ageRating": "3+",
    "price": 14.99,
    "discountedPrice": 4.79,
    "onSale": true,
    "image": "https://api.noroff.dev/images/gamehub/0-ping-pong-championship.jpg",
    "tags": ["gamehub", "game"],
    "favorite": true},


];